### ISSUE TITLE
MAX1000 does not support 1-bit passive serial scheme

### ISSUE THREAD

**Issue by k-macdonald** [micro-FPGA/litex-boards#6]
Very excited about the max1000 fpga support files here, however I've been unable to get them to work. Please forgive if I'm missing something simple, as I'm very new to this stuff.

I've pulled the master branch into my litex repo, and ran the targets/max1000.py file. I had to modify the integrated_main_ram_size (which was commented out) to get it to run to this point (otherwise I get that the RAM doesn't fit onto the device), and then modify the litex soc_core.py file to use the LM32 cpu. Other than these two changes, everything is entirely a fresh pull from github. After a minute or so of compilation, I get the following error:

```
Device 10M08SAU169 does not support 1-bit Passive Serial scheme
Error (213050): Convert Programming Files was NOT successful -- refer to messages that appear above this message for more information
Error: Quartus Prime Convert_programming_file was unsuccessful. 1 error, 0 warnings
```

Based on this comment (https://forum.trenz-electronic.de/index.php?topic=1111.0) I also tried running with the CPU type VexRiscv, which gives me the following error:

```
Error (170012): Fitter requires 543 LABs to implement the design, but the device contains only 504 LABs
Error (171000): Can't fit design in device
Error: Quartus Prime Fitter was unsuccessful. 2 errors, 12 warnings
```

I've downloaded/added to my $PATH the Quartus Lite version 18.1.0, build 625 and am running on Ubuntu 16.04. 

If you have any thoughts or ideas of things I should investigate, I'd really appreciate it! Thanks!

**Comment by Frank-Buss** [comment]
I got the same error. But you can still configure the FPGA. See [here](https://github.com/FrankBuss/litex-baremetal-test) for an example. You can also use the Quartus programmer application to flash it to the FPGA configuration flash memory (CFM), so that it gets loaded automatically on power up. Don't know if this should be possible with the LiteX tools as well.

**Comment by k-macdonald** [comment]
Thanks for the note, Frank! Glad to hear this wasn't just me. I ended up getting this to work (tested on both ubuntu 16.04 & 18.04) by going into the litex/litex/build/altera/quartus.py file, and then commenting out the following lines of code:

```
if [ -f "{build_name}.sof" ]
then
     quartus_cpf -c {build_name}.sof {build_name}.rbf
fi
```

It seems that the 1-bit passive serial scheme has something to do with the .rbf file. I'm programming the board with libxsvf, therefore only need to convert the .pof directly to .svf (using the command line quartus_cpf command), with no need for .rbf. This allowed me to use the litex toolchain.

**Comment by Frank-Buss** [comment]
Ok, litex would be another repository. Maybe @enjoy-digital knows what to do. For the record, when the max1000.py script finishes, there are 2 files: top.pof and top.sof. To program the SRAM of the Cyclone, which lasts until power off, you can do this:
```
quartus_pgm -m jtag -o "p;soc_basesoc_max1000/gateware/top.sof"
```
To program the internal CFM flash, which is automatically loaded to SRAM at power on, you can do this:
```
quartus_pgm -m jtag -o 'Pv;soc_basesoc_max1000/gateware/top.pof@1'
```
After programming the internal flash, the new configuration is loaded into SRAM as well, without manual power off/on cycling.

If the LiteX tools are supposed to support these two programming things, then it should be added/fixed somewhere.

I tested it with Quartus 19.1 on Linux, and with the 16k version of the Cyclone. The 8k version currently results in a fitter error. I guess this is related to the bug @AnttiLukats mentioned somewhere, that the ROM of the BIOS is generated as logic instead of block RAM. With my [PR](https://github.com/micro-FPGA/litex-boards/pull/7) you can specify for which version it should be compiled (current version without the PR uses 8k).

**Comment by AnttiLukats** [comment]
This is not a bug, Intel flash devices do not have active serial mode, you can just use POF files to write the flash content.

**Comment by Frank-Buss** [comment]
But would be nice, if the toolchain wouldn't try to do it, if it is not supported :-)
